# conda env create -f conda_environment_baargin.yml
name: baargin
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - pyyaml
  - gitpython
  - requests
  - gzip
  - biopython>=1.78
  - numpy>=1.22
  - python>=3.8.0
  - nextflow>=22.04.0
